# Generated by Django 3.1 on 2021-09-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sale_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintSelectProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='productsize',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.hintselectproduct'),
        ),
    ]
